name: my_project_env
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - tensorflow
  - keras
  - pytorch
  - opencv
  - pip
  - pip:
    - ultralytics
    - labelme
